/**
 * Per-mood log-priors for `CharacterClassifier`, in CHARACTER_MOODS order.
 *
 * GENERATED by `scripts/calibrate/character-priors.calib.ts` (npm run
 * calibrate:priors). Do not edit by hand.
 *
 * Why: real music is not spread evenly over the valence/arousal/tension/pulse
 * cube (it clusters, e.g. loud and bright), so with flat priors a few moods absorb
 * most songs. The priors are tuned so that, over a reference set of UNLABELLED
 * audio, the 14 moods win about equally often. No human labels are involved.
 *
 * Order: serene, tender, dreamy, melancholic, brooding, mysterious, groove, playful, uplifting, euphoric, driving, tense, aggressive, epic
 * Share of reference frames before: serene 3%, tender 3%, dreamy 2%, melancholic 15%, brooding 16%, mysterious 8%, groove 7%, playful 1%, uplifting 8%, euphoric 2%, driving 3%, tense 8%, aggressive 2%, epic 22%
 * Share of reference frames after:  serene 6%, tender 6%, dreamy 7%, melancholic 7%, brooding 8%, mysterious 8%, groove 6%, playful 7%, uplifting 7%, euphoric 7%, driving 7%, tense 9%, aggressive 8%, epic 7%
 */
export const CHARACTER_PRIORS: readonly number[] = [1.19, 1.268, 0.543, -0.16, -1.585, -0.821, 0.669, 1.449, 0.505, 1.327, 0.525, -0.632, 0.636, -1.558]
export const CHARACTER_PRIORS_SOURCE = "balanced on 184 unlabelled tracks (Jamendo + PMEmo pool fold, track-weighted), cap +/-2.5; entropy 0.87 -> 1.00; generated 2026-09-20"
