/**
 * Reference-population percentile tables for `TimbreDescriptors.ts`.
 *
 * GENERATED by `scripts/calibrate/timbre-quantiles.calib.ts` (npm run
 * calibrate:timbre). Do not edit by hand.
 *
 * Each array holds a value at equally spaced probabilities 0, 1/(n-1), ..., 1.
 * Built from audio FEATURES only, never from human or LLM labels.
 */
export interface TimbreCalibration {
  /** Per input feature: value at each probability knot (equally spaced probabilities 0..1). */
  features: Record<string, readonly number[]>
  /** Per output composite: value at each probability knot. */
  composites: {
    harsh?: readonly number[]
    busy?: readonly number[]
    sparse?: readonly number[]
  }
  /** Provenance of the tables, for humans. */
  source: string
}

export const TIMBRE_CALIBRATION: TimbreCalibration = {
  features: {
    loudness: [0, 0.22808, 0.38554, 0.49804, 0.58406, 0.65672, 0.71528, 0.76561, 0.80889, 0.84695, 0.87971, 0.90858, 0.93348, 0.95392, 0.96972, 0.98126, 0.98943, 0.99484, 0.99799, 0.99954, 1],
    flux: [0, 0.00905, 0.0194, 0.02988, 0.04015, 0.05078, 0.062, 0.07406, 0.08677, 0.10055, 0.11554, 0.13205, 0.15045, 0.17063, 0.1943, 0.22092, 0.25278, 0.29132, 0.34099, 0.40697, 0.97037],
    roughness: [0.01698, 0.1497, 0.17615, 0.19388, 0.20871, 0.22164, 0.23343, 0.24468, 0.25521, 0.26544, 0.27547, 0.28551, 0.29596, 0.30672, 0.31811, 0.33045, 0.34458, 0.36162, 0.38378, 0.41894, 0.65825],
    tonalness: [0.00018, 0.09009, 0.14068, 0.18027, 0.2152, 0.24844, 0.28063, 0.31564, 0.35017, 0.3849, 0.42117, 0.45841, 0.49584, 0.53613, 0.57828, 0.62495, 0.67547, 0.72776, 0.78154, 0.84351, 0.99071],
    modeAmbiguity: [0, 0, 0, 0, 0, 0, 0, 0, 0.05124, 0.12654, 0.20624, 0.28176, 0.36526, 0.4403, 0.51687, 0.59699, 0.67518, 0.75282, 0.82835, 0.91604, 0.99999],
  },
  composites: {
    harsh: [0.00598, 0.17953, 0.25185, 0.30969, 0.35638, 0.39144, 0.4202, 0.44748, 0.46884, 0.4894, 0.50936, 0.52883, 0.55045, 0.57109, 0.59418, 0.61754, 0.64568, 0.67658, 0.71603, 0.7788, 0.95153],
    busy: [0.07348, 0.232, 0.27564, 0.31346, 0.34489, 0.37331, 0.39841, 0.42214, 0.44493, 0.46579, 0.48631, 0.50592, 0.52604, 0.54494, 0.56763, 0.59003, 0.60841, 0.63346, 0.66579, 0.70756, 0.90366],
    sparse: [0, 0.02099, 0.03933, 0.06261, 0.08751, 0.10831, 0.12817, 0.15264, 0.17945, 0.2059, 0.23442, 0.26453, 0.29484, 0.32324, 0.35242, 0.3843, 0.4187, 0.4592, 0.50866, 0.5763, 0.97044],
  },
  source: "184 unlabelled tracks (Jamendo + PMEmo pool fold, first 90 s each), 225577 frames, generated 2026-09-21",
}
