/**
 * Generates `src/audio/characterPriors.ts`: per-mood log-priors that make the 14 named moods win about
 * equally often over a reference set of UNLABELLED audio. No human labels are used.
 *
 *   npm run calibrate:priors        (needs the pool feature caches from `npm run calibrate:quantiles`)
 *
 * Method: replay the emotion estimator over every cached reference track (first 90 s), sample its
 * character point once per second, then iterate `prior_k += eta * (ln target - ln share_k)` on the
 * argmax shares with each TRACK weighted equally (so long Jamendo tracks do not swamp short PMEmo
 * clips), capped so a prior can never override a prototype outright.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { PRIORS, computeInstantDist } from '../../src/audio/CharacterClassifier'
import { CHARACTER_MOODS, type CharacterInput } from '../../src/audio/characterTypes'
import { EmotionDimensionEstimator } from '../../src/audio/emotionDimensions'
import { REPLAY_STRIDE, framesFromCache, type FeatureCache } from './emotion'
import { normalizedEntropy } from './stats'

const ROOT = resolve(__dirname, '../..')
const POOL = join(ROOT, 'corpus/emotion/cache-pool')
const OUT = join(ROOT, 'src/audio/characterPriors.ts')
const N = CHARACTER_MOODS.length
/** A prior never exceeds this many nats: enough to rebalance, not enough to override a prototype. */
const CAP = 2.5
const ETA = 0.2
const ITERS = 600

describe.skipIf(!existsSync(POOL))('character priors', () => {
  it('balances the moods on the unlabelled reference set', () => {
    const tracks: CharacterInput[][] = []
    const dt = REPLAY_STRIDE / 60
    for (const f of readdirSync(POOL).filter((n) => n.endsWith('.json'))) {
      const cache = JSON.parse(readFileSync(join(POOL, f), 'utf8')) as FeatureCache
      const est = new EmotionDimensionEstimator()
      const pts: CharacterInput[] = []
      let next = 8
      for (const fr of framesFromCache(cache)) {
        est.update(fr, dt)
        if (fr.t >= next && est.read().valid) {
          pts.push({ ...est.read() })
          next = fr.t + 1
        }
      }
      if (pts.length >= 5) tracks.push(pts)
    }
    expect(tracks.length).toBeGreaterThan(30)

    const out = new Float64Array(N)
    const shares = (): number[] => {
      const s = new Array<number>(N).fill(0)
      for (const pts of tracks) {
        const w = 1 / pts.length / tracks.length
        for (const p of pts) {
          computeInstantDist(p, out)
          let best = 0
          for (let i = 1; i < N; i++) if (out[i] > out[best]) best = i
          s[best] += w
        }
      }
      return s
    }

    PRIORS.fill(0)
    const before = shares()
    const target = 1 / N
    for (let it = 0; it < ITERS; it++) {
      const s = shares()
      let dev = 0
      for (let k = 0; k < N; k++) {
        dev = Math.max(dev, Math.abs(s[k] - target))
        PRIORS[k] = Math.max(-CAP, Math.min(CAP, PRIORS[k] + ETA * (Math.log(target) - Math.log(Math.max(s[k], 0.004)))))
      }
      if (dev < 0.015) break
    }
    const after = shares()
    const fmt = (a: number[]) => CHARACTER_MOODS.map((m, i) => `${m} ${(a[i] * 100).toFixed(0)}%`).join(', ')
    const priors = Array.from(PRIORS, (p) => Number(p.toFixed(3)))
    const source =
      `balanced on ${tracks.length} unlabelled tracks (Jamendo + PMEmo pool fold, track-weighted), cap +/-${CAP}; ` +
      `entropy ${normalizedEntropy(before).toFixed(2)} -> ${normalizedEntropy(after).toFixed(2)}; generated ${new Date().toISOString().slice(0, 10)}`
    writeFileSync(
      OUT,
      [
        '/**',
        ' * Per-mood log-priors for `CharacterClassifier`, in CHARACTER_MOODS order.',
        ' *',
        ' * GENERATED by `scripts/calibrate/character-priors.calib.ts` (npm run',
        ' * calibrate:priors). Do not edit by hand.',
        ' *',
        ' * Why: real music is not spread evenly over the valence/arousal/tension/pulse',
        ' * cube (it clusters, e.g. loud and bright), so with flat priors a few moods absorb',
        ' * most songs. The priors are tuned so that, over a reference set of UNLABELLED',
        ' * audio, the 14 moods win about equally often. No human labels are involved.',
        ' *',
        ` * Order: ${CHARACTER_MOODS.join(', ')}`,
        ` * Share of reference frames before: ${fmt(before)}`,
        ` * Share of reference frames after:  ${fmt(after)}`,
        ' */',
        `export const CHARACTER_PRIORS: readonly number[] = [${priors.join(', ')}]`,
        `export const CHARACTER_PRIORS_SOURCE = ${JSON.stringify(source)}`,
        '',
      ].join('\n'),
    )
    console.log(`before: ${fmt(before)}\nafter:  ${fmt(after)}\npriors: ${priors.join(', ')}\n${source}`)
  })
})
